; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs = secrets.ini

[env:esp32s3_gemini]
platform = espressif32@6.7.0
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags = 
	-D CONFIG_GEMINI_API_KEY='"${secrets.gemini_api_key}"'
	-D CONFIG_WIFI_SSID='"${secrets.wifi_ssid}"'
	-D CONFIG_WIFI_PASSWORD='"${secrets.wifi_password}"'

[env:native]
platform = native
test_framework = unity
lib_deps = 
	https://github.com/meekrosoft/fff.git
	throwtheswitch/Unity@^2.6.0
build_src_filter = 
	+<*>
	-<../src/>
build_flags = 
	-std=gnu11
	-Wall
	-Wextra
	-I lib/Esp32WifiManager
	-I lib/MemoryPool
	-I .pio/libdeps/native/Unity/src
	-I .pio/build/native/unity_config_build
	-I test/test_Esp32WifiManager/Fakes
  -I .pio/libdeps/native/fff/src

[secrets]
gemini_api_key = AIzaSyBfrRcE4WtG6M-QZ9AEceixFj9XG7JmrLY
wifi_ssid = BT-HPAK9R
wifi_password = hAfMVAYE43ytrt
