  ; PlatformIO Project Configuration File
  ;
  ;   Build options: build flags, source filter
  ;   Upload options: custom upload port, speed and extra flags
  ;   Library options: dependencies, extra library storages
  ;   Advanced options: extra scripting
  ;
  ; Please visit documentation for the other options and examples
  ; https://docs.platformio.org/page/projectconf.html

[platformio]
  ; Load private credentials from a separate, untracked file
  extra_configs = secrets.ini

[env:esp32s3_gemini]
  platform = espressif32@6.7.0
  board = esp32-s3-devkitc-1 ; Change this if you use a different ESP32-S3 board
  framework = espidf
  monitor_speed = 115200
  ; Define macros for the C code using values from secrets.ini
  build_flags =
    -D CONFIG_GEMINI_API_KEY='"${secrets.gemini_api_key}"'
    -D CONFIG_WIFI_SSID='"${secrets.wifi_ssid}"'
    -D CONFIG_WIFI_PASSWORD='"${secrets.wifi_password}"'

[env:native]
platform = native
test_framework = unity
lib_deps =
    MemoryPool
    WifiManager
test_build_src = yes

build_flags =
    -std=gnu11
    -Wall
    -Wextra
    # --- Project paths ---
    -I lib/WifiManager
    -I lib/MemoryPool
    -I test/CONFIG_GEMINI_API_KEY
    
    -I /home/matthew/.platformio/packages/framework-espidf/components/esp_common/include
    -I /home/matthew/.platformio/packages/framework-espidf/components/esp_system/include
    -I /home/matthew/.platformio/packages/framework-espidf/components/log/include
    -I /home/matthew/.platformio/packages/framework-espidf/components/newlib/platform_include
    -I /home/matthew/.platformio/packages/framework-espidf/components/freertos/config/include/freertos
    -I /home/matthew/.platformio/packages/framework-espidf/components/freertos/esp_additions/include/freertos
    -I /home/matthew/.platformio/packages/framework-espidf/components/freertos/FreeRTOS-Kernel-SMP/include
    -I $PROJECT_BUILD_DIR/esp32s3_gemini/config

build_src_filter =
    +<*>
    +<../test>
    -<../src>

extra_scripts = post:extra_script.py
