; This file is not tracked by Git.
;
; Store your private credentials here WITHOUT quotes.
; The build system will add the necessary quotes.
[secrets]
gemini_api_key = AIzaSyBfrRcE4WtG6M-QZ9AEceixFj9XG7JmrLY
wifi_ssid = BT-HPAK9R
wifi_password = hAfMVAYE43ytrt
